[project]
name = "pdf-remediation"
version = "0.2.0"
description = "Automated PDF remediation to meet WCAG 2.2 using the PDFix SDK."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.0",
    "parallelbar>=2.5",
    "pathlib>=1.0.1",
    "pdfix-sdk>=8.7.8",
    "plotext>=5.3.2",
    "python-dotenv>=1.2.1",
    "python-on-whales>=0.80.0",
]

[project.scripts]
fleet = "pdf_remediation.fleet:main"
pdf-remediation = "pdf_remediation:main"
fix = "pdf_remediation.fix:main"
font_fix = "pdf_remediation.font_fix:main"
font_fix_pdfix = "pdf_remediation.font_fix_pdfix:main"
get_latest_files = "pdf_remediation.get_latest_files:main"
go = "pdf_remediation.go:main"
init = "pdf_remediation.init:main"
license = "pdf_remediation.license:main"
readyset = "pdf_remediation.readyset:main"
reprocess = "pdf_remediation.reprocess:main"
reset = "pdf_remediation.reset:main"
solo-fix = "pdf_worker.solo_fix:main"
solo-validate = "pdf_worker.solo_validate:main"
status = "pdf_remediation.status:main"
validate = "pdf_remediation.validate:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pylint>=4.0.4",
]
