[project]
name = "pdf-remediation"
version = "0.2.0"
description = "Automated PDF remediation to meet WCAG 2.2 using the PDFix SDK."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.0",
    "parallelbar>=2.5",
    "pathlib>=1.0.1",
    "pdfix-sdk>=8.7.8",
    "plotext>=5.3.2",
    "python-dotenv>=1.2.1",
    "python-on-whales>=0.80.0",
]

[project.scripts]
pdf-remediation = "pdf_remediation:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pylint>=4.0.4",
]

[tool.uv.sources]
pdfix-sdk = { url = "https://pdfix-public-storage.s3.eu-west-1.amazonaws.com/public/builds/pdfix-sdk/master/1b054bb41c13734ac1035ae4d7c3b9a47aa31b03/python/pdfix_sdk-8.7.17.tar.gz" }
