[project]
name = "pdf-remediation"
version = "0.2.0"
description = "Automated PDF remediation to meet WCAG 2.2 using the PDFix SDK."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.0",
    "parallelbar>=2.5",
    "pathlib>=1.0.1",
    "pdfix-sdk>=8.7.8",
    "plotext>=5.3.2",
    "python-dotenv>=1.2.1",
    "python-on-whales>=0.80.0",
]

[project.scripts]
pdf-remediation = "pdf_remediation:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pylint>=4.0.4",
]

[tool.uv.sources]
pdfix-sdk = { url = "https://dl.pdfix.net/builds/pdfix-sdk/release/v8.7.16/5e8e051252e91625e039ad90393d35b6b9f7c2fd/python/pdfix_sdk-8.7.16.tar.gz" }
